### ISSUE TITLE
Java::excptn: A Java exception occurred: java.lang.NoSuchMethodError: org.slf4j.Logger.isTraceEnabled()Z

### ISSUE THREAD

**Issue by julio-pope** [zbjornson/MongoDBLink#10]
Hello, I am trying to test your code but it's appear this problem every time I use functions like "DatabaseNames[]", "FindDocuments[collection]", etc.:

Java::excptn: A Java exception occurred: java.lang.NoSuchMethodError: org.slf4j.Logger.isTraceEnabled()Z
at com.mongodb.diagnostics.logging.SLF4JLogger.isTraceEnabled(SLF4JLogger.java:36)
at com.mongodb.connection.DefaultConnectionPool.getPooledConnection(DefaultConnectionPool.java:258)
at com.mongodb.connection.DefaultConnectionPool.get(DefaultConnectionPool.java:93)
at com.mongodb.connection.DefaultConnectionPool.get(DefaultConnectionPool.java:82)
at com.mongodb.connection.DefaultServer.getConnection(DefaultServer.java:72)
at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.getConnection(ClusterBinding.java:86)
at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:237)
at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:212)
at com.mongodb.operation.ListDatabasesOperation.execute(ListDatabasesOperation.java:101)
at com.mongodb.operation.ListDatabasesOperation.execute(ListDatabasesOperation.java:53)
at com.mongodb.Mongo.execute(Mongo.java:772)
at com.mongodb.Mongo$2.execute(Mongo.java:759)
at com.mongodb.OperationIterable.iterator(OperationIterable.java:47)
at com.mongodb.OperationIterable.forEach(OperationIterable.java:70)
at com.mongodb.MappingIterable.forEach(MappingIterable.java:50)
at com.mongodb.MappingIterable.into(MappingIterable.java:60)
at com.mongodb.Mongo.getDatabaseNames(Mongo.java:436).

Do you know which is the problem? How can I solve the problem?

Thank you!!

**Comment by zbjornson** [comment]
I think that might be because you have an old SLF4J (<1.2.12) on your java classpath. Can you post your `JavaClassPath[]` please? MongoDB will only use SLF4J (logging) if the class is present, so the solution would be to either upgrade to a newer version or remove it from your classpath so MongoDB doesn't try to load it in the first place.
