### ISSUE TITLE
Suggestion for a AggregateDocument function

### ISSUE THREAD

**Issue by rodrigomurta** [zbjornson/MongoDBLink#6]
Hi Zach,
Do you have plans to create a `AggregateDocument` function?
It would be really cool if I could do things like:

```
AggregateDocument[ myColletion
        ,{"$project" ->  {"author" -> 1}}
        ,{"$group" -> {"_id" -> "$author", "count" -> {"$sum" -> 1}}}
        ,{"$sort" -> {"count" -> -1}}
        ,{"$limit" -> 5}
]
```

tks
Murta

**Comment by zbjornson** [comment]
Hadn't gotten that far, but yes, thanks for the suggestion. I'll play with some designs soon.

(If you need that functionality immediately, you can access the the underlying java object for the collection with `collection["collection"]` and use jlink to call the aggregation commands that you need.)

Semi-related, I keep forgetting to add Sort options to all the query functions (just made #7 for that).

**Comment by julio-pope** [comment]
Hello, I am trying to test your code but it's appear this problem every time I use functions like "DatabaseNames[]", "FindDocuments[collection]", etc.:

Java::excptn: A Java exception occurred: java.lang.NoSuchMethodError: org.slf4j.Logger.isTraceEnabled()Z
	at com.mongodb.diagnostics.logging.SLF4JLogger.isTraceEnabled(SLF4JLogger.java:36)
	at com.mongodb.connection.DefaultConnectionPool.getPooledConnection(DefaultConnectionPool.java:258)
	at com.mongodb.connection.DefaultConnectionPool.get(DefaultConnectionPool.java:93)
	at com.mongodb.connection.DefaultConnectionPool.get(DefaultConnectionPool.java:82)
	at com.mongodb.connection.DefaultServer.getConnection(DefaultServer.java:72)
	at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.getConnection(ClusterBinding.java:86)
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:237)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:212)
	at com.mongodb.operation.ListDatabasesOperation.execute(ListDatabasesOperation.java:101)
	at com.mongodb.operation.ListDatabasesOperation.execute(ListDatabasesOperation.java:53)
	at com.mongodb.Mongo.execute(Mongo.java:772)
	at com.mongodb.Mongo$2.execute(Mongo.java:759)
	at com.mongodb.OperationIterable.iterator(OperationIterable.java:47)
	at com.mongodb.OperationIterable.forEach(OperationIterable.java:70)
	at com.mongodb.MappingIterable.forEach(MappingIterable.java:50)
	at com.mongodb.MappingIterable.into(MappingIterable.java:60)
	at com.mongodb.Mongo.getDatabaseNames(Mongo.java:436).

Do you know which is the problem? How can I solve the problem?

Thank you!!

**Comment by zbjornson** [comment]
@julio-pope can you move that to a new issue please? I don't think it's related to this topic.

**Comment by zbjornson** [comment]
(I will move this answer when you move the question, but for now--)

I think that might be because you have an old SLF4J (<1.2.12) on your java classpath. Can you post your `JavaClassPath[]` please? MongoDB will only use SLF4J (logging) if the class is present, so the solution would be to either upgrade to a newer version or remove it from your classpath so MongoDB doesn't try to load it in the first place.

**Comment by zbjornson** [comment]
Feedback from Mike H on syntax:

Change the OP example to a list of stages:

```Mathematica
AggregateDocuments[ myColletion,{
        ,{"$project" ->  {"author" -> 1}}
        ,{"$group" -> {"_id" -> "$author", "count" -> {"$sum" -> 1}}}
        ,{"$sort" -> {"count" -> -1}}
        ,{"$limit" -> 5}
        }
]
```

or more generally `AggregateDocuments[ myColletion, myPipeline]`, where myPipeline is a list containing one or more pipeline steps which are lists. Each pipeline stage takes the form `{$operator -> operand}` where the operand is normally a list.
